### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by usmaann** [littleflow3r/keras-elmo-glove#1]
hello thanks for sharing, i am unable to run both codes.

When I run Glove get below error

![image](https://user-images.githubusercontent.com/38275359/51454121-3e0fc980-1d97-11e9-8de6-9a768a92a2a7.png)
 

and Getting below error when running , Elmo.

![image](https://user-images.githubusercontent.com/38275359/51454137-508a0300-1d97-11e9-98e5-8bb64f255924.png)

Please advise how to fix both issues

**Comment by susantiyuni** [comment]
Hi, sorry I didn't notice you opened this issue.
I've just run the code and it works without errors in my machine. 

Do you use the aclIMDB data as in my code? It seems that the problem is in the data, where the input data is a list but it has zero length (that's why it gave error list index out of range when keras utils tried to access isinstance data[0]). 

I think you can debug the code by checking the content and the type of the x_train and x_test.

**Comment by susantiyuni** [comment]
Hi, just an addition. I found someone with same error https://stackoverflow.com/questions/52407777/indexerror-list-index-out-of-range-keras-tokenizer. 
You can probably refer to how he solved his.
